CLEAR ALL
CLOSE ALL

USE c:\turtle\aya\integrad.000\cabevent IN 0 NOUPDATE
USE c:\turtle\aya\integrad.000\detavent IN 0 NOUPDATE

USE c:\turtle\aya\integrad.000\cabenotc IN 0 NOUPDATE
USE c:\turtle\aya\integrad.000\detanotc IN 0 NOUPDATE

USE c:\turtle\aya\integrad.000\cabecomp IN 0 NOUPDATE
USE c:\turtle\aya\integrad.000\detacomp IN 0 NOUPDATE

USE c:\turtle\aya\integrad.000\cabenotp IN 0 NOUPDATE
USE c:\turtle\aya\integrad.000\detanotp IN 0 NOUPDATE

