del *.tmp
del tm*.*
del *.fxp
del *.bak

ren FrmArticulo.sct FrmArticulo.sct
ren FrmArticulo.scx FrmArticulo.scx
ren FrmBarrio.sct FrmBarrio.sct
ren FrmBarrio.scx FrmBarrio.scx
ren FrmBuscarArticulo.sct FrmBuscarArticulo.sct
ren FrmBuscarArticulo.scx FrmBuscarArticulo.scx
ren FrmBuscarBarrio.sct FrmBuscarBarrio.sct
ren FrmBuscarBarrio.scx FrmBuscarBarrio.scx
ren FrmBuscarCiudad.sct FrmBuscarCiudad.sct
ren FrmBuscarCiudad.scx FrmBuscarCiudad.scx
ren FrmBuscarCliente.sct FrmBuscarCliente.sct
ren FrmBuscarCliente.scx FrmBuscarCliente.scx
ren FrmBuscarCobrador.sct FrmBuscarCobrador.sct
ren FrmBuscarCobrador.scx FrmBuscarCobrador.scx
ren FrmBuscarDepar.sct FrmBuscarDepar.sct
ren FrmBuscarDepar.scx FrmBuscarDepar.scx
ren FrmBuscarDeposito.sct FrmBuscarDeposito.sct
ren FrmBuscarDeposito.scx FrmBuscarDeposito.scx
ren FrmBuscarFamilia.sct FrmBuscarFamilia.sct
ren FrmBuscarFamilia.scx FrmBuscarFamilia.scx
ren FrmBuscarMaquina.sct FrmBuscarMaquina.sct
ren FrmBuscarMaquina.scx FrmBuscarMaquina.scx
ren FrmBuscarMarca.sct FrmBuscarMarca.sct
ren FrmBuscarMarca.scx FrmBuscarMarca.scx
ren FrmBuscarMarcaTaller.sct FrmBuscarMarcaTaller.sct
ren FrmBuscarMarcaTaller.scx FrmBuscarMarcaTaller.scx
ren FrmBuscarMecanico.sct FrmBuscarMecanico.sct
ren FrmBuscarMecanico.scx FrmBuscarMecanico.scx
ren FrmBuscarModelo.sct FrmBuscarModelo.sct
ren FrmBuscarModelo.scx FrmBuscarModelo.scx
ren FrmBuscarMotivoCliente.sct FrmBuscarMotivoCliente.sct
ren FrmBuscarMotivoCliente.scx FrmBuscarMotivoCliente.scx
ren FrmBuscarPais.sct FrmBuscarPais.sct
ren FrmBuscarPais.scx FrmBuscarPais.scx
ren FrmBuscarPlazo.sct FrmBuscarPlazo.sct
ren FrmBuscarPlazo.scx FrmBuscarPlazo.scx
ren FrmBuscarProveedor.sct FrmBuscarProveedor.sct
ren FrmBuscarProveedor.scx FrmBuscarProveedor.scx
ren FrmBuscarRubro.sct FrmBuscarRubro.sct
ren FrmBuscarRubro.scx FrmBuscarRubro.scx
ren FrmBuscarRuta.sct FrmBuscarRuta.sct
ren FrmBuscarRuta.scx FrmBuscarRuta.scx
ren FrmBuscarSubRubro.sct FrmBuscarSubRubro.sct
ren FrmBuscarSubRubro.scx FrmBuscarSubRubro.scx
ren FrmBuscarSucursal.sct FrmBuscarSucursal.sct
ren FrmBuscarSucursal.scx FrmBuscarSucursal.scx
ren FrmBuscarUnidadMedida.sct FrmBuscarUnidadMedida.sct
ren FrmBuscarUnidadMedida.scx FrmBuscarUnidadMedida.scx
ren FrmBuscarVendedor.sct FrmBuscarVendedor.sct
ren FrmBuscarVendedor.scx FrmBuscarVendedor.scx
ren FrmCiudad.sct FrmCiudad.sct
ren FrmCiudad.scx FrmCiudad.scx
ren FrmCliente.sct FrmCliente.sct
ren FrmCliente.scx FrmCliente.scx
ren FrmCobrador.sct FrmCobrador.sct
ren FrmCobrador.scx FrmCobrador.scx
ren FrmDepar.sct FrmDepar.sct
ren FrmDepar.scx FrmDepar.scx
ren FrmDeposito.sct FrmDeposito.sct
ren FrmDeposito.scx FrmDeposito.scx
ren FrmEscritorio.sct FrmEscritorio.sct
ren FrmEscritorio.scx FrmEscritorio.scx
ren FrmFamilia.sct FrmFamilia.sct
ren FrmFamilia.scx FrmFamilia.scx
ren FrmLogin.sct FrmLogin.sct
ren FrmLogin.scx FrmLogin.scx
ren FrmMaquina.sct FrmMaquina.sct
ren FrmMaquina.scx FrmMaquina.scx
ren FrmMarca.sct FrmMarca.sct
ren FrmMarca.scx FrmMarca.scx
ren FrmMarcaTaller.sct FrmMarcaTaller.sct
ren FrmMarcaTaller.scx FrmMarcaTaller.scx
ren FrmMecanico.sct FrmMecanico.sct
ren FrmMecanico.scx FrmMecanico.scx
ren FrmModelo.sct FrmModelo.sct
ren FrmModelo.scx FrmModelo.scx
ren FrmMotivoCliente.sct FrmMotivoCliente.sct
ren FrmMotivoCliente.scx FrmMotivoCliente.scx
ren FrmPais.sct FrmPais.sct
ren FrmPais.scx FrmPais.scx
ren FrmPlazo.sct FrmPlazo.sct
ren FrmPlazo.scx FrmPlazo.scx
ren FrmProveedor.sct FrmProveedor.sct
ren FrmProveedor.scx FrmProveedor.scx
ren FrmRubro.sct FrmRubro.sct
ren FrmRubro.scx FrmRubro.scx
ren FrmRuta.sct FrmRuta.sct
ren FrmRuta.scx FrmRuta.scx
ren FrmSubRubro.sct FrmSubRubro.sct
ren FrmSubRubro.scx FrmSubRubro.scx
ren FrmSucursal.sct FrmSucursal.sct
ren FrmSucursal.scx FrmSucursal.scx
ren FrmUnidadMedida.sct FrmUnidadMedida.sct
ren FrmUnidadMedida.scx FrmUnidadMedida.scx
ren FrmVendedor.sct FrmVendedor.sct
ren FrmVendedor.scx FrmVendedor.scx